function matUtterance = simulateMovement(obj, uttPlan, myPlotFlag)
%simulates tongue movement with control parameters (muscles/time)

    seq = ['r' uttPlan.target];
    
    % delta lambda values; order is GGP GGA HYO STY VER SL IL
    matUtterance = simul_tongue_adapt_jaw(obj.model, ...
        seq, ...
        uttPlan.deltaLambdaGGP, ...
        uttPlan.deltaLambdaGGA, ...
        uttPlan.deltaLambdaHYO, ...
        uttPlan.deltaLambdaSTY, ...
        uttPlan.deltaLambdaVER, ...
        uttPlan.deltaLambdaSL, ...
        uttPlan.deltaLambdaIL, ...
        uttPlan.durTransition, ...
        uttPlan.durHold, ...
        uttPlan.jawRotation, ...
        uttPlan.lipProtrusion, ...
        uttPlan.lipRotation, ...
        uttPlan.hyoid_mov, ...
        myPlotFlag);
    
end
