function [mat_obs, matUtterance] = simulateMovement(obj, uttPlan, myPlotFlag)
%simulate movement / produce a MATLAB structure containing a full utterance
    %    
    %input arguments:
    %
    %   - uttPlan   : utterance plan containing timing and muscle activations 
    %   - myPlotFlag: flag to decide between simulating movement with (value: true)
    %                 or without (value: false) graphics (note that graphics is
    %                 time-consuming, movement will takes 50% more time
    %                 with graffics turned ON
    %
    seq = ['r' uttPlan.target];
    
    % delta lambda values; order is GGP GGA HYO STY VER SL IL
    [mat_obs, matUtterance] = simul_tongue_adapt_jaw(obj.model, ...
        seq, ...
        uttPlan.deltaLambdaGGP, ...
        uttPlan.deltaLambdaGGA, ...
        uttPlan.deltaLambdaHYO, ...
        uttPlan.deltaLambdaSTY, ...
        uttPlan.deltaLambdaVER, ...
        uttPlan.deltaLambdaSL, ...
        uttPlan.deltaLambdaIL, ...
        uttPlan.durTransition, ...
        uttPlan.durHold, ...
        uttPlan.jawRotation, ...
        uttPlan.lipProtrusion, ...
        uttPlan.lipRotation, ...
        uttPlan.hyoid_mov, ...
        myPlotFlag);
    
end
