function [snd, fs] = sythese_brad(af, F0Contour, F0, Dur)
% produces audio signal from area function (formerly sythese_brad.m)
%
% file_area_function : mat file generated by smooth_area_function with nb_tubes=44
% F0Contour = 0 1 2 (Corresponds to 3 types of contours proposed by Brad
% Story (0 creates a monotone – F0 will be exactly constant over the
% duration of the simulation. 1 creates an F0 contour as a statement, 2 is
% a question)
% F0 = Pitch in Hz
% Dur = Duration of the sound in s
% Generates Kelly-Lochbaum acoustic synthesis with Brad Story's Programs
% (March 2009)

% written 09/2012 by RW (PILIOS)

fs = 44100;

init_params % Brad's program

q.areas = af.tube_area;
q.dxnew= af.tube_length; % Length of the tubes (the same for all tubes because KL Model)
q.F0contour = F0Contour;
q.fotarg = F0;
q.td = Dur;

[snd,ugn,t,r,tv,areas,lgths,fo,p] = ModerMouthExecTremor(q);
