Description of elast2
Home > model_adapt_jaw > elast2.m
elast2
PURPOSE
Calcule la matrice d'elasticite A0 en fonction des activites des
SYNOPSIS
function elast2 = elast2(activGGA, activGGP, activHyo, activStylo,activSL, activVert, ncontact)
DESCRIPTION
 Calcule la matrice d'elasticite A0 en fonction des activites des
 differents muscles : E vaut 15 kPa pour un element au repos et 250
 kPa pour un element contracte au maximum.
 Ceci correspond a multiplier lambda et mu jusqu'a 16 fois leurs
 valeurs initiales.
CROSS-REFERENCE INFORMATION
This function calls:
elast2 Calcule la matrice d'elasticite A0 en fonction des activites des
This function is called by:
elast2 Calcule la matrice d'elasticite A0 en fonction des activites des
udot3_adapt_jaw CV - 03/03/99
SOURCE CODE
function elast2 = elast2(activGGA, activGGP, activHyo, activStylo, ...
    activSL, activVert, ncontact)
% Calcule la matrice d'elasticite A0 en fonction des activites des
% differents muscles : E vaut 15 kPa pour un element au repos et 250
% kPa pour un element contracte au maximum.
% Ceci correspond a multiplier lambda et mu jusqu'a 16 fois leurs
% valeurs initiales.
% Parametres d'entree :
% -  Les activation des muscles
% -  ncontact qui est un vecteur contenant 0 et les indices des noeuds qui
%    entrent en contact avec le palais : les coefficients de la
%    matrice d'elasticite dependent en effet des points fixes de
%    l'element considere.
    global X0Y0
    global NN
    global MM
    global fact
    global lambda
    global mu
    global ordre
    global IA
    global IB
    global IC
    global ID
    global IE
    AA = zeros(1,(2*NN*MM)^2);
    activtot = [activGGA, activGGP, activHyo, activStylo, activSL, activVert];
    AA = elast_c(NN, MM, fact, ordre, lambda, mu, IA, IB, IC, ID, IE, ...
        activtot, X0Y0, ncontact);
    elast2 = reshape(AA, 2*NN*MM, 2*NN*MM);
end